package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
//
// Code generated by github.com/99designs/gqlgen version v0.17.64

import (
	"context"
	"f1betting/betting_system"
	"f1betting/user_management"
	"fmt"
	"strconv"

	"f1betting/user_api/graph/model"
)

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	userID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, err
	}

	user, err := user_management.GetUserByID(ctx, r.Conn, userID)
	if err != nil {
		return nil, err
	}

	phoneNumber := *user.PhoneNumber
	taxId := *user.TaxID
	country := *user.Country
	preferredCurrency := *user.PreferredCurrency
	favoriteTeam := *user.FavoriteTeam
	profilePictureUrl := *user.ProfilePictureURL

	return &model.User{
		ID:                strconv.FormatInt(user.ID, 10),
		FullName:          user.FullName,
		Email:             user.Email,
		Username:          user.Username,
		DateOfBirth:       user.DateOfBirth.String(),
		PhoneNumber:       &phoneNumber,
		GovernmentID:      user.GovernmentID,
		Address:           user.Address,
		TaxID:             &taxId,
		AccountStatus:     model.AccountStatus(user.AccountStatus),
		RegistrationDate:  user.RegistrationDate.String(),
		Role:              model.UserRole(user.Role),
		EmailVerified:     user.EmailVerified,
		Country:           &country,
		PreferredCurrency: &preferredCurrency,
		FavoriteTeam:      &favoriteTeam,
		ProfilePictureURL: &profilePictureUrl,
		Balance:           user.Balance,
	}, nil
}

// UserByEmail is the resolver for the userByEmail field.
func (r *queryResolver) UserByEmail(ctx context.Context, email string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: UserByEmail - userByEmail"))
}

// UserByUsername is the resolver for the userByUsername field.
func (r *queryResolver) UserByUsername(ctx context.Context, username string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: UserByUsername - userByUsername"))
}

// FastestLapBetsAndVisualizedPayout is the resolver for the fastestLapBetsAndVisualizedPayout field.
func (r *queryResolver) FastestLapBetsAndVisualizedPayout(ctx context.Context, sessionID int32, userID string) (*model.FastestLapBetsAndVisualizedPayout, error) {
	// Get all bets for session

	sessionBets, err := betting_system.GetFastestLapBetsByRace(ctx, r.Conn, int64(sessionID), "PENDING")
	if err != nil {
		return nil, err
	}

	var result []*model.FastestLapBet

	// Convert session bets to GraphQL model
	for _, bet := range *sessionBets {
		result = append(result, &model.FastestLapBet{
			ID:          strconv.FormatInt(bet.ID, 10),
			UserID:      userID,
			SessionID:   int32(bet.SessionID),
			DriverID:    bet.DriverID,
			Status:      model.BetStatus(bet.Status),
			Amount:      bet.Amount,
			BettingPool: int32(bet.BettingPool),
			CreatedAt:   bet.CreateAt.String(),
		})
	}

	userIDInt64, err := strconv.ParseInt(userID, 10, 64)
	if err != nil {
		return nil, err
	}
	userPayouts, err := betting_system.GetFastestLapUserVisualizedPayout(ctx, r.Conn, userIDInt64, int(sessionID))

	payouts := make([]*model.FastestLapUserPayout, 0)
	for _, payout := range *userPayouts {
		payouts = append(payouts, &model.FastestLapUserPayout{
			DriverID: strconv.Itoa(int(payout.DriverID)),
			Payout:   payout.Payout,
		})
	}

	return &model.FastestLapBetsAndVisualizedPayout{
		FastestLapBets:   result,
		VisualizedPayout: payouts,
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
