// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/betting_system.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PodiumBetRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId            int32    `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FirstPosition        int32    `protobuf:"varint,3,opt,name=first_position,json=firstPosition,proto3" json:"first_position,omitempty"`
	SecondPosition       int32    `protobuf:"varint,4,opt,name=second_position,json=secondPosition,proto3" json:"second_position,omitempty"`
	ThirdPosition        int32    `protobuf:"varint,5,opt,name=third_position,json=thirdPosition,proto3" json:"third_position,omitempty"`
	BettingPool          int32    `protobuf:"varint,6,opt,name=betting_pool,json=bettingPool,proto3" json:"betting_pool,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PodiumBetRequest) Reset()         { *m = PodiumBetRequest{} }
func (m *PodiumBetRequest) String() string { return proto.CompactTextString(m) }
func (*PodiumBetRequest) ProtoMessage()    {}
func (*PodiumBetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_533987502b87e742, []int{0}
}

func (m *PodiumBetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodiumBetRequest.Unmarshal(m, b)
}
func (m *PodiumBetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodiumBetRequest.Marshal(b, m, deterministic)
}
func (m *PodiumBetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodiumBetRequest.Merge(m, src)
}
func (m *PodiumBetRequest) XXX_Size() int {
	return xxx_messageInfo_PodiumBetRequest.Size(m)
}
func (m *PodiumBetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PodiumBetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PodiumBetRequest proto.InternalMessageInfo

func (m *PodiumBetRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PodiumBetRequest) GetSessionId() int32 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *PodiumBetRequest) GetFirstPosition() int32 {
	if m != nil {
		return m.FirstPosition
	}
	return 0
}

func (m *PodiumBetRequest) GetSecondPosition() int32 {
	if m != nil {
		return m.SecondPosition
	}
	return 0
}

func (m *PodiumBetRequest) GetThirdPosition() int32 {
	if m != nil {
		return m.ThirdPosition
	}
	return 0
}

func (m *PodiumBetRequest) GetBettingPool() int32 {
	if m != nil {
		return m.BettingPool
	}
	return 0
}

type PolePositionBetRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId            int32    `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	DriverId             int32    `protobuf:"varint,3,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	BettingPool          int32    `protobuf:"varint,4,opt,name=betting_pool,json=bettingPool,proto3" json:"betting_pool,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PolePositionBetRequest) Reset()         { *m = PolePositionBetRequest{} }
func (m *PolePositionBetRequest) String() string { return proto.CompactTextString(m) }
func (*PolePositionBetRequest) ProtoMessage()    {}
func (*PolePositionBetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_533987502b87e742, []int{1}
}

func (m *PolePositionBetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PolePositionBetRequest.Unmarshal(m, b)
}
func (m *PolePositionBetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PolePositionBetRequest.Marshal(b, m, deterministic)
}
func (m *PolePositionBetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PolePositionBetRequest.Merge(m, src)
}
func (m *PolePositionBetRequest) XXX_Size() int {
	return xxx_messageInfo_PolePositionBetRequest.Size(m)
}
func (m *PolePositionBetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PolePositionBetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PolePositionBetRequest proto.InternalMessageInfo

func (m *PolePositionBetRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PolePositionBetRequest) GetSessionId() int32 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *PolePositionBetRequest) GetDriverId() int32 {
	if m != nil {
		return m.DriverId
	}
	return 0
}

func (m *PolePositionBetRequest) GetBettingPool() int32 {
	if m != nil {
		return m.BettingPool
	}
	return 0
}

type RainBetRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId            int32    `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RainPrediction       bool     `protobuf:"varint,3,opt,name=rain_prediction,json=rainPrediction,proto3" json:"rain_prediction,omitempty"`
	BettingPool          int32    `protobuf:"varint,4,opt,name=betting_pool,json=bettingPool,proto3" json:"betting_pool,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RainBetRequest) Reset()         { *m = RainBetRequest{} }
func (m *RainBetRequest) String() string { return proto.CompactTextString(m) }
func (*RainBetRequest) ProtoMessage()    {}
func (*RainBetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_533987502b87e742, []int{2}
}

func (m *RainBetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RainBetRequest.Unmarshal(m, b)
}
func (m *RainBetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RainBetRequest.Marshal(b, m, deterministic)
}
func (m *RainBetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RainBetRequest.Merge(m, src)
}
func (m *RainBetRequest) XXX_Size() int {
	return xxx_messageInfo_RainBetRequest.Size(m)
}
func (m *RainBetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RainBetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RainBetRequest proto.InternalMessageInfo

func (m *RainBetRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *RainBetRequest) GetSessionId() int32 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *RainBetRequest) GetRainPrediction() bool {
	if m != nil {
		return m.RainPrediction
	}
	return false
}

func (m *RainBetRequest) GetBettingPool() int32 {
	if m != nil {
		return m.BettingPool
	}
	return 0
}

type RetirementBetRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId            int32    `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	DriverId             int32    `protobuf:"varint,3,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	BettingPool          int32    `protobuf:"varint,4,opt,name=betting_pool,json=bettingPool,proto3" json:"betting_pool,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetirementBetRequest) Reset()         { *m = RetirementBetRequest{} }
func (m *RetirementBetRequest) String() string { return proto.CompactTextString(m) }
func (*RetirementBetRequest) ProtoMessage()    {}
func (*RetirementBetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_533987502b87e742, []int{3}
}

func (m *RetirementBetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetirementBetRequest.Unmarshal(m, b)
}
func (m *RetirementBetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetirementBetRequest.Marshal(b, m, deterministic)
}
func (m *RetirementBetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetirementBetRequest.Merge(m, src)
}
func (m *RetirementBetRequest) XXX_Size() int {
	return xxx_messageInfo_RetirementBetRequest.Size(m)
}
func (m *RetirementBetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RetirementBetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RetirementBetRequest proto.InternalMessageInfo

func (m *RetirementBetRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *RetirementBetRequest) GetSessionId() int32 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *RetirementBetRequest) GetDriverId() int32 {
	if m != nil {
		return m.DriverId
	}
	return 0
}

func (m *RetirementBetRequest) GetBettingPool() int32 {
	if m != nil {
		return m.BettingPool
	}
	return 0
}

type FastestLapBetRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId            int32    `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	DriverId             int32    `protobuf:"varint,3,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	BettingPool          int32    `protobuf:"varint,4,opt,name=betting_pool,json=bettingPool,proto3" json:"betting_pool,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FastestLapBetRequest) Reset()         { *m = FastestLapBetRequest{} }
func (m *FastestLapBetRequest) String() string { return proto.CompactTextString(m) }
func (*FastestLapBetRequest) ProtoMessage()    {}
func (*FastestLapBetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_533987502b87e742, []int{4}
}

func (m *FastestLapBetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FastestLapBetRequest.Unmarshal(m, b)
}
func (m *FastestLapBetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FastestLapBetRequest.Marshal(b, m, deterministic)
}
func (m *FastestLapBetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FastestLapBetRequest.Merge(m, src)
}
func (m *FastestLapBetRequest) XXX_Size() int {
	return xxx_messageInfo_FastestLapBetRequest.Size(m)
}
func (m *FastestLapBetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FastestLapBetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FastestLapBetRequest proto.InternalMessageInfo

func (m *FastestLapBetRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *FastestLapBetRequest) GetSessionId() int32 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *FastestLapBetRequest) GetDriverId() int32 {
	if m != nil {
		return m.DriverId
	}
	return 0
}

func (m *FastestLapBetRequest) GetBettingPool() int32 {
	if m != nil {
		return m.BettingPool
	}
	return 0
}

type LapTimingBetRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId            int32    `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	LapNumber            int32    `protobuf:"varint,3,opt,name=lap_number,json=lapNumber,proto3" json:"lap_number,omitempty"`
	DriverId             int32    `protobuf:"varint,4,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	BettingPool          int32    `protobuf:"varint,5,opt,name=betting_pool,json=bettingPool,proto3" json:"betting_pool,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LapTimingBetRequest) Reset()         { *m = LapTimingBetRequest{} }
func (m *LapTimingBetRequest) String() string { return proto.CompactTextString(m) }
func (*LapTimingBetRequest) ProtoMessage()    {}
func (*LapTimingBetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_533987502b87e742, []int{5}
}

func (m *LapTimingBetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LapTimingBetRequest.Unmarshal(m, b)
}
func (m *LapTimingBetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LapTimingBetRequest.Marshal(b, m, deterministic)
}
func (m *LapTimingBetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LapTimingBetRequest.Merge(m, src)
}
func (m *LapTimingBetRequest) XXX_Size() int {
	return xxx_messageInfo_LapTimingBetRequest.Size(m)
}
func (m *LapTimingBetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LapTimingBetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LapTimingBetRequest proto.InternalMessageInfo

func (m *LapTimingBetRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *LapTimingBetRequest) GetSessionId() int32 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *LapTimingBetRequest) GetLapNumber() int32 {
	if m != nil {
		return m.LapNumber
	}
	return 0
}

func (m *LapTimingBetRequest) GetDriverId() int32 {
	if m != nil {
		return m.DriverId
	}
	return 0
}

func (m *LapTimingBetRequest) GetBettingPool() int32 {
	if m != nil {
		return m.BettingPool
	}
	return 0
}

type BetResponse struct {
	BetId                int64    `protobuf:"varint,1,opt,name=bet_id,json=betId,proto3" json:"bet_id,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Amount               float64  `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BetResponse) Reset()         { *m = BetResponse{} }
func (m *BetResponse) String() string { return proto.CompactTextString(m) }
func (*BetResponse) ProtoMessage()    {}
func (*BetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_533987502b87e742, []int{6}
}

func (m *BetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BetResponse.Unmarshal(m, b)
}
func (m *BetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BetResponse.Marshal(b, m, deterministic)
}
func (m *BetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BetResponse.Merge(m, src)
}
func (m *BetResponse) XXX_Size() int {
	return xxx_messageInfo_BetResponse.Size(m)
}
func (m *BetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BetResponse proto.InternalMessageInfo

func (m *BetResponse) GetBetId() int64 {
	if m != nil {
		return m.BetId
	}
	return 0
}

func (m *BetResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *BetResponse) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type UserRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_533987502b87e742, []int{7}
}

func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (m *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(m, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type SessionRequest struct {
	SessionId            int32    `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionRequest) Reset()         { *m = SessionRequest{} }
func (m *SessionRequest) String() string { return proto.CompactTextString(m) }
func (*SessionRequest) ProtoMessage()    {}
func (*SessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_533987502b87e742, []int{8}
}

func (m *SessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionRequest.Unmarshal(m, b)
}
func (m *SessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionRequest.Marshal(b, m, deterministic)
}
func (m *SessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionRequest.Merge(m, src)
}
func (m *SessionRequest) XXX_Size() int {
	return xxx_messageInfo_SessionRequest.Size(m)
}
func (m *SessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SessionRequest proto.InternalMessageInfo

func (m *SessionRequest) GetSessionId() int32 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

type BalanceResponse struct {
	Balance              float64  `protobuf:"fixed64,1,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BalanceResponse) Reset()         { *m = BalanceResponse{} }
func (m *BalanceResponse) String() string { return proto.CompactTextString(m) }
func (*BalanceResponse) ProtoMessage()    {}
func (*BalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_533987502b87e742, []int{9}
}

func (m *BalanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceResponse.Unmarshal(m, b)
}
func (m *BalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceResponse.Marshal(b, m, deterministic)
}
func (m *BalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceResponse.Merge(m, src)
}
func (m *BalanceResponse) XXX_Size() int {
	return xxx_messageInfo_BalanceResponse.Size(m)
}
func (m *BalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceResponse proto.InternalMessageInfo

func (m *BalanceResponse) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

type Bet struct {
	BetType   string `protobuf:"bytes,1,opt,name=bet_type,json=betType,proto3" json:"bet_type,omitempty"`
	Id        int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	UserId    int64  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId int32  `protobuf:"varint,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Types that are valid to be assigned to BetDetails:
	//
	//	*Bet_Podium
	//	*Bet_Driver
	//	*Bet_Rain
	//	*Bet_LapTiming
	BetDetails           isBet_BetDetails       `protobuf_oneof:"bet_details"`
	Amount               float64                `protobuf:"fixed64,9,opt,name=amount,proto3" json:"amount,omitempty"`
	Status               string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	BettingPool          int32                  `protobuf:"varint,11,opt,name=betting_pool,json=bettingPool,proto3" json:"betting_pool,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Bet) Reset()         { *m = Bet{} }
func (m *Bet) String() string { return proto.CompactTextString(m) }
func (*Bet) ProtoMessage()    {}
func (*Bet) Descriptor() ([]byte, []int) {
	return fileDescriptor_533987502b87e742, []int{10}
}

func (m *Bet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bet.Unmarshal(m, b)
}
func (m *Bet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bet.Marshal(b, m, deterministic)
}
func (m *Bet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bet.Merge(m, src)
}
func (m *Bet) XXX_Size() int {
	return xxx_messageInfo_Bet.Size(m)
}
func (m *Bet) XXX_DiscardUnknown() {
	xxx_messageInfo_Bet.DiscardUnknown(m)
}

var xxx_messageInfo_Bet proto.InternalMessageInfo

func (m *Bet) GetBetType() string {
	if m != nil {
		return m.BetType
	}
	return ""
}

func (m *Bet) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Bet) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Bet) GetSessionId() int32 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

type isBet_BetDetails interface {
	isBet_BetDetails()
}

type Bet_Podium struct {
	Podium *PodiumBetDetails `protobuf:"bytes,5,opt,name=podium,proto3,oneof"`
}

type Bet_Driver struct {
	Driver *DriverBetDetails `protobuf:"bytes,6,opt,name=driver,proto3,oneof"`
}

type Bet_Rain struct {
	Rain *RainBetDetails `protobuf:"bytes,7,opt,name=rain,proto3,oneof"`
}

type Bet_LapTiming struct {
	LapTiming *LapTimingBetDetails `protobuf:"bytes,8,opt,name=lap_timing,json=lapTiming,proto3,oneof"`
}

func (*Bet_Podium) isBet_BetDetails() {}

func (*Bet_Driver) isBet_BetDetails() {}

func (*Bet_Rain) isBet_BetDetails() {}

func (*Bet_LapTiming) isBet_BetDetails() {}

func (m *Bet) GetBetDetails() isBet_BetDetails {
	if m != nil {
		return m.BetDetails
	}
	return nil
}

func (m *Bet) GetPodium() *PodiumBetDetails {
	if x, ok := m.GetBetDetails().(*Bet_Podium); ok {
		return x.Podium
	}
	return nil
}

func (m *Bet) GetDriver() *DriverBetDetails {
	if x, ok := m.GetBetDetails().(*Bet_Driver); ok {
		return x.Driver
	}
	return nil
}

func (m *Bet) GetRain() *RainBetDetails {
	if x, ok := m.GetBetDetails().(*Bet_Rain); ok {
		return x.Rain
	}
	return nil
}

func (m *Bet) GetLapTiming() *LapTimingBetDetails {
	if x, ok := m.GetBetDetails().(*Bet_LapTiming); ok {
		return x.LapTiming
	}
	return nil
}

func (m *Bet) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Bet) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Bet) GetBettingPool() int32 {
	if m != nil {
		return m.BettingPool
	}
	return 0
}

func (m *Bet) GetCreatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Bet) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Bet_Podium)(nil),
		(*Bet_Driver)(nil),
		(*Bet_Rain)(nil),
		(*Bet_LapTiming)(nil),
	}
}

type PodiumBetDetails struct {
	FirstPosition        int32    `protobuf:"varint,1,opt,name=first_position,json=firstPosition,proto3" json:"first_position,omitempty"`
	SecondPosition       int32    `protobuf:"varint,2,opt,name=second_position,json=secondPosition,proto3" json:"second_position,omitempty"`
	ThirdPosition        int32    `protobuf:"varint,3,opt,name=third_position,json=thirdPosition,proto3" json:"third_position,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PodiumBetDetails) Reset()         { *m = PodiumBetDetails{} }
func (m *PodiumBetDetails) String() string { return proto.CompactTextString(m) }
func (*PodiumBetDetails) ProtoMessage()    {}
func (*PodiumBetDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_533987502b87e742, []int{11}
}

func (m *PodiumBetDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodiumBetDetails.Unmarshal(m, b)
}
func (m *PodiumBetDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodiumBetDetails.Marshal(b, m, deterministic)
}
func (m *PodiumBetDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodiumBetDetails.Merge(m, src)
}
func (m *PodiumBetDetails) XXX_Size() int {
	return xxx_messageInfo_PodiumBetDetails.Size(m)
}
func (m *PodiumBetDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_PodiumBetDetails.DiscardUnknown(m)
}

var xxx_messageInfo_PodiumBetDetails proto.InternalMessageInfo

func (m *PodiumBetDetails) GetFirstPosition() int32 {
	if m != nil {
		return m.FirstPosition
	}
	return 0
}

func (m *PodiumBetDetails) GetSecondPosition() int32 {
	if m != nil {
		return m.SecondPosition
	}
	return 0
}

func (m *PodiumBetDetails) GetThirdPosition() int32 {
	if m != nil {
		return m.ThirdPosition
	}
	return 0
}

type DriverBetDetails struct {
	DriverId             int32    `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DriverBetDetails) Reset()         { *m = DriverBetDetails{} }
func (m *DriverBetDetails) String() string { return proto.CompactTextString(m) }
func (*DriverBetDetails) ProtoMessage()    {}
func (*DriverBetDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_533987502b87e742, []int{12}
}

func (m *DriverBetDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DriverBetDetails.Unmarshal(m, b)
}
func (m *DriverBetDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DriverBetDetails.Marshal(b, m, deterministic)
}
func (m *DriverBetDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DriverBetDetails.Merge(m, src)
}
func (m *DriverBetDetails) XXX_Size() int {
	return xxx_messageInfo_DriverBetDetails.Size(m)
}
func (m *DriverBetDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_DriverBetDetails.DiscardUnknown(m)
}

var xxx_messageInfo_DriverBetDetails proto.InternalMessageInfo

func (m *DriverBetDetails) GetDriverId() int32 {
	if m != nil {
		return m.DriverId
	}
	return 0
}

type RainBetDetails struct {
	RainPrediction       bool     `protobuf:"varint,1,opt,name=rain_prediction,json=rainPrediction,proto3" json:"rain_prediction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RainBetDetails) Reset()         { *m = RainBetDetails{} }
func (m *RainBetDetails) String() string { return proto.CompactTextString(m) }
func (*RainBetDetails) ProtoMessage()    {}
func (*RainBetDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_533987502b87e742, []int{13}
}

func (m *RainBetDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RainBetDetails.Unmarshal(m, b)
}
func (m *RainBetDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RainBetDetails.Marshal(b, m, deterministic)
}
func (m *RainBetDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RainBetDetails.Merge(m, src)
}
func (m *RainBetDetails) XXX_Size() int {
	return xxx_messageInfo_RainBetDetails.Size(m)
}
func (m *RainBetDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_RainBetDetails.DiscardUnknown(m)
}

var xxx_messageInfo_RainBetDetails proto.InternalMessageInfo

func (m *RainBetDetails) GetRainPrediction() bool {
	if m != nil {
		return m.RainPrediction
	}
	return false
}

type LapTimingBetDetails struct {
	LapNumber            int32    `protobuf:"varint,1,opt,name=lap_number,json=lapNumber,proto3" json:"lap_number,omitempty"`
	DriverId             int32    `protobuf:"varint,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LapTimingBetDetails) Reset()         { *m = LapTimingBetDetails{} }
func (m *LapTimingBetDetails) String() string { return proto.CompactTextString(m) }
func (*LapTimingBetDetails) ProtoMessage()    {}
func (*LapTimingBetDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_533987502b87e742, []int{14}
}

func (m *LapTimingBetDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LapTimingBetDetails.Unmarshal(m, b)
}
func (m *LapTimingBetDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LapTimingBetDetails.Marshal(b, m, deterministic)
}
func (m *LapTimingBetDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LapTimingBetDetails.Merge(m, src)
}
func (m *LapTimingBetDetails) XXX_Size() int {
	return xxx_messageInfo_LapTimingBetDetails.Size(m)
}
func (m *LapTimingBetDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_LapTimingBetDetails.DiscardUnknown(m)
}

var xxx_messageInfo_LapTimingBetDetails proto.InternalMessageInfo

func (m *LapTimingBetDetails) GetLapNumber() int32 {
	if m != nil {
		return m.LapNumber
	}
	return 0
}

func (m *LapTimingBetDetails) GetDriverId() int32 {
	if m != nil {
		return m.DriverId
	}
	return 0
}

type UserBetsResponse struct {
	Bets                 []*Bet   `protobuf:"bytes,1,rep,name=bets,proto3" json:"bets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserBetsResponse) Reset()         { *m = UserBetsResponse{} }
func (m *UserBetsResponse) String() string { return proto.CompactTextString(m) }
func (*UserBetsResponse) ProtoMessage()    {}
func (*UserBetsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_533987502b87e742, []int{15}
}

func (m *UserBetsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserBetsResponse.Unmarshal(m, b)
}
func (m *UserBetsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserBetsResponse.Marshal(b, m, deterministic)
}
func (m *UserBetsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserBetsResponse.Merge(m, src)
}
func (m *UserBetsResponse) XXX_Size() int {
	return xxx_messageInfo_UserBetsResponse.Size(m)
}
func (m *UserBetsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserBetsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserBetsResponse proto.InternalMessageInfo

func (m *UserBetsResponse) GetBets() []*Bet {
	if m != nil {
		return m.Bets
	}
	return nil
}

type SessionBetsResponse struct {
	Bets                 []*Bet   `protobuf:"bytes,1,rep,name=bets,proto3" json:"bets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionBetsResponse) Reset()         { *m = SessionBetsResponse{} }
func (m *SessionBetsResponse) String() string { return proto.CompactTextString(m) }
func (*SessionBetsResponse) ProtoMessage()    {}
func (*SessionBetsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_533987502b87e742, []int{16}
}

func (m *SessionBetsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionBetsResponse.Unmarshal(m, b)
}
func (m *SessionBetsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionBetsResponse.Marshal(b, m, deterministic)
}
func (m *SessionBetsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionBetsResponse.Merge(m, src)
}
func (m *SessionBetsResponse) XXX_Size() int {
	return xxx_messageInfo_SessionBetsResponse.Size(m)
}
func (m *SessionBetsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionBetsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SessionBetsResponse proto.InternalMessageInfo

func (m *SessionBetsResponse) GetBets() []*Bet {
	if m != nil {
		return m.Bets
	}
	return nil
}

func init() {
	proto.RegisterType((*PodiumBetRequest)(nil), "betting.PodiumBetRequest")
	proto.RegisterType((*PolePositionBetRequest)(nil), "betting.PolePositionBetRequest")
	proto.RegisterType((*RainBetRequest)(nil), "betting.RainBetRequest")
	proto.RegisterType((*RetirementBetRequest)(nil), "betting.RetirementBetRequest")
	proto.RegisterType((*FastestLapBetRequest)(nil), "betting.FastestLapBetRequest")
	proto.RegisterType((*LapTimingBetRequest)(nil), "betting.LapTimingBetRequest")
	proto.RegisterType((*BetResponse)(nil), "betting.BetResponse")
	proto.RegisterType((*UserRequest)(nil), "betting.UserRequest")
	proto.RegisterType((*SessionRequest)(nil), "betting.SessionRequest")
	proto.RegisterType((*BalanceResponse)(nil), "betting.BalanceResponse")
	proto.RegisterType((*Bet)(nil), "betting.Bet")
	proto.RegisterType((*PodiumBetDetails)(nil), "betting.PodiumBetDetails")
	proto.RegisterType((*DriverBetDetails)(nil), "betting.DriverBetDetails")
	proto.RegisterType((*RainBetDetails)(nil), "betting.RainBetDetails")
	proto.RegisterType((*LapTimingBetDetails)(nil), "betting.LapTimingBetDetails")
	proto.RegisterType((*UserBetsResponse)(nil), "betting.UserBetsResponse")
	proto.RegisterType((*SessionBetsResponse)(nil), "betting.SessionBetsResponse")
}

func init() {
	proto.RegisterFile("proto/betting_system.proto", fileDescriptor_533987502b87e742)
}

var fileDescriptor_533987502b87e742 = []byte{
	// 924 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x2e, 0xf5, 0x67, 0x6b, 0x64, 0x53, 0xce, 0x3a, 0x3f, 0xb4, 0x1a, 0x23, 0x2e, 0x81, 0x34,
	0x06, 0x8a, 0x4a, 0xa8, 0x53, 0xa0, 0xc8, 0xa1, 0x45, 0xc3, 0x1a, 0x89, 0x5d, 0x04, 0x81, 0xc2,
	0xb8, 0x97, 0x5e, 0x04, 0x4a, 0x1c, 0xbb, 0x0b, 0x48, 0x5c, 0x96, 0x3b, 0x32, 0xe0, 0x47, 0xe8,
	0xa5, 0xe8, 0xa1, 0x8f, 0xd1, 0x57, 0xea, 0xad, 0x40, 0x5f, 0x23, 0xe0, 0xee, 0x92, 0x22, 0x25,
	0x5a, 0x76, 0x00, 0x1f, 0x72, 0x32, 0xf8, 0xed, 0x37, 0xe3, 0x6f, 0x67, 0x66, 0xe7, 0x13, 0xf4,
	0xe2, 0x44, 0x90, 0x18, 0x8c, 0x91, 0x88, 0x47, 0x17, 0x23, 0x79, 0x25, 0x09, 0x67, 0x7d, 0x05,
	0xb2, 0x0d, 0x83, 0xf6, 0x9e, 0x5c, 0x08, 0x71, 0x31, 0xc5, 0x81, 0x82, 0xc7, 0xf3, 0xf3, 0x01,
	0xf1, 0x19, 0x4a, 0x0a, 0x66, 0xb1, 0x66, 0xba, 0xff, 0x59, 0xb0, 0x33, 0x14, 0x21, 0x9f, 0xcf,
	0x3c, 0x24, 0x1f, 0x7f, 0x9f, 0xa3, 0x24, 0xf6, 0x08, 0x36, 0xe6, 0x12, 0x93, 0x11, 0x0f, 0x1d,
	0xeb, 0xc0, 0x3a, 0xac, 0xfb, 0xad, 0xf4, 0xf3, 0x34, 0x64, 0xfb, 0x00, 0x12, 0xa5, 0xe4, 0x22,
	0x4a, 0xcf, 0x6a, 0x07, 0xd6, 0x61, 0xd3, 0x6f, 0x1b, 0xe4, 0x34, 0x64, 0x4f, 0xc1, 0x3e, 0xe7,
	0x89, 0xa4, 0x51, 0x2c, 0x24, 0x27, 0x2e, 0x22, 0xa7, 0xae, 0x28, 0xdb, 0x0a, 0x1d, 0x1a, 0x90,
	0x3d, 0x83, 0xae, 0xc4, 0x89, 0x88, 0xc2, 0x05, 0xaf, 0xa1, 0x78, 0xb6, 0x86, 0x73, 0xe2, 0x53,
	0xb0, 0xe9, 0x37, 0x9e, 0x14, 0x78, 0x4d, 0x9d, 0x4f, 0xa1, 0x39, 0xed, 0x0b, 0xd8, 0xca, 0xaa,
	0x10, 0x0b, 0x31, 0x75, 0x5a, 0x8a, 0xd4, 0x31, 0xd8, 0x50, 0x88, 0xa9, 0xfb, 0x97, 0x05, 0x0f,
	0x87, 0x62, 0x8a, 0x59, 0xcc, 0x1d, 0x5c, 0xf6, 0x73, 0x68, 0x87, 0x09, 0xbf, 0xd4, 0x91, 0xfa,
	0x9e, 0x9b, 0x1a, 0x38, 0x0d, 0x57, 0x24, 0x35, 0x56, 0x25, 0xfd, 0x6d, 0x81, 0xed, 0x07, 0xfc,
	0x2e, 0xa4, 0x3c, 0x83, 0x6e, 0x12, 0xf0, 0x68, 0x14, 0x27, 0x18, 0xf2, 0x49, 0x5e, 0xf8, 0x4d,
	0xdf, 0x4e, 0xe1, 0x61, 0x8e, 0xde, 0x46, 0xd6, 0x9f, 0x16, 0xdc, 0xf7, 0x91, 0x78, 0x82, 0x33,
	0x8c, 0xe8, 0x13, 0xa8, 0x53, 0x2a, 0xe8, 0x55, 0x20, 0x09, 0x25, 0xbd, 0x09, 0xe2, 0x4f, 0x40,
	0xd0, 0x3f, 0x16, 0xec, 0xbe, 0x09, 0xe2, 0x33, 0x3e, 0xe3, 0xd1, 0xc5, 0x1d, 0xe8, 0xd9, 0x07,
	0x98, 0x06, 0xf1, 0x28, 0x9a, 0xcf, 0xc6, 0x98, 0x18, 0x41, 0xed, 0x69, 0x10, 0xbf, 0x55, 0x40,
	0x59, 0x6e, 0xe3, 0x06, 0xb9, 0xcd, 0x55, 0xb9, 0x67, 0xd0, 0x51, 0x22, 0x65, 0x2c, 0x22, 0x89,
	0xec, 0x01, 0xb4, 0xc6, 0x48, 0x0b, 0x91, 0xcd, 0x31, 0xd2, 0x69, 0xc8, 0x1e, 0x42, 0x4b, 0x52,
	0x40, 0x73, 0xa9, 0xf4, 0xb5, 0x7d, 0xf3, 0x95, 0xe2, 0xc1, 0x4c, 0xcc, 0x23, 0x52, 0xc2, 0x2c,
	0xdf, 0x7c, 0xb9, 0x5f, 0x42, 0xe7, 0x17, 0x89, 0xc9, 0x4d, 0x77, 0x77, 0x07, 0x60, 0xbf, 0xd7,
	0x37, 0xcd, 0xa8, 0xe5, 0x6a, 0x58, 0x4b, 0xd5, 0x70, 0xbf, 0x82, 0xae, 0x17, 0x4c, 0x83, 0x68,
	0x82, 0xb9, 0x64, 0x07, 0x36, 0xc6, 0x1a, 0x52, 0x74, 0xcb, 0xcf, 0x3e, 0xdd, 0x7f, 0xeb, 0x50,
	0xf7, 0x90, 0xd8, 0x1e, 0x6c, 0xa6, 0x97, 0xa2, 0xab, 0x58, 0x53, 0xda, 0x7e, 0xba, 0x01, 0xcf,
	0xae, 0x62, 0x64, 0x36, 0xd4, 0x4c, 0xd1, 0xeb, 0x7e, 0x8d, 0x87, 0x45, 0xa5, 0xf5, 0x35, 0x5d,
	0x6a, 0x2c, 0x77, 0xe9, 0x39, 0xb4, 0x62, 0xb5, 0x27, 0x55, 0x8d, 0x3b, 0x47, 0x7b, 0x7d, 0x53,
	0xe4, 0x7e, 0xbe, 0x3e, 0x8f, 0x91, 0x02, 0x3e, 0x95, 0x27, 0x9f, 0xf9, 0x86, 0x9a, 0x06, 0xe9,
	0x56, 0xa9, 0x9d, 0x54, 0x0c, 0x3a, 0x56, 0x70, 0x39, 0x48, 0x53, 0xd9, 0xd7, 0xd0, 0x48, 0x9f,
	0xad, 0xb3, 0xa1, 0x42, 0x1e, 0xe5, 0x21, 0x66, 0x59, 0x2c, 0x02, 0x14, 0x8d, 0x7d, 0xaf, 0xc7,
	0x87, 0xd4, 0x38, 0x3a, 0x9b, 0x2a, 0xe8, 0x71, 0x1e, 0x54, 0x1c, 0xd4, 0x45, 0x64, 0x3a, 0x5e,
	0x1a, 0x2e, 0x34, 0xb8, 0x5d, 0x6c, 0x70, 0x61, 0x20, 0xa0, 0x34, 0x10, 0xcb, 0x13, 0xd7, 0x59,
	0x99, 0x38, 0xf6, 0x02, 0x60, 0x92, 0x60, 0x40, 0x18, 0x8e, 0x02, 0x72, 0xb6, 0x94, 0xa2, 0x5e,
	0x5f, 0x3b, 0x51, 0x3f, 0x73, 0xa2, 0xfe, 0x59, 0xe6, 0x44, 0x7e, 0xdb, 0xb0, 0x5f, 0x92, 0xb7,
	0x0d, 0x69, 0xa6, 0x51, 0xa8, 0x95, 0xba, 0x7f, 0x14, 0xdd, 0xc9, 0xc8, 0xaf, 0x70, 0x19, 0xeb,
	0x96, 0x2e, 0x53, 0xbb, 0xa5, 0xcb, 0xd4, 0x2b, 0x5c, 0xc6, 0x1d, 0xc0, 0xce, 0x72, 0xd3, 0xca,
	0x6f, 0xd3, 0x2a, 0xbf, 0x4d, 0xf7, 0x45, 0xbe, 0xdf, 0x33, 0x7a, 0xc5, 0x9e, 0xb6, 0xaa, 0xf6,
	0xb4, 0xfb, 0xae, 0xbc, 0x61, 0xb2, 0xf8, 0xf2, 0xa6, 0xb0, 0xd6, 0x6e, 0x8a, 0xda, 0x92, 0x9a,
	0x6f, 0x61, 0x27, 0x7d, 0xb0, 0x1e, 0x92, 0xcc, 0x1f, 0xd6, 0x01, 0x34, 0xc6, 0x48, 0xd2, 0xb1,
	0x0e, 0xea, 0x87, 0x9d, 0xa3, 0xad, 0x7c, 0x68, 0xd2, 0x7d, 0xa1, 0x4e, 0xdc, 0xef, 0x60, 0xd7,
	0x3c, 0xdf, 0x8f, 0x0b, 0x3c, 0xfa, 0xbf, 0x09, 0xb6, 0xa7, 0xd1, 0xf7, 0x98, 0x5c, 0xf2, 0x09,
	0x32, 0x0f, 0xba, 0x3f, 0xa9, 0x46, 0xe7, 0x1d, 0x65, 0x15, 0x8f, 0xc8, 0xac, 0x89, 0xde, 0xfd,
	0x52, 0xd2, 0xec, 0x1f, 0xbf, 0x85, 0x07, 0x59, 0x8e, 0x92, 0x99, 0xb3, 0x27, 0x85, 0x4c, 0x55,
	0x36, 0x7f, 0x4d, 0xbe, 0x1f, 0x60, 0x5b, 0xe7, 0x33, 0x9d, 0x62, 0x2b, 0xcf, 0x6d, 0x7d, 0xfc,
	0xcf, 0xb0, 0x6b, 0xe2, 0x8b, 0x96, 0xc9, 0xf6, 0x17, 0x59, 0x2a, 0xac, 0xf4, 0xa6, 0x5c, 0x25,
	0xb7, 0x2b, 0xe4, 0xaa, 0x72, 0xc1, 0x6b, 0x72, 0x9d, 0x00, 0xd3, 0xb9, 0x8a, 0x63, 0xc4, 0xaa,
	0xd7, 0xc2, 0xfa, 0x4c, 0xc7, 0x70, 0xef, 0x35, 0x52, 0x3a, 0x3a, 0x2f, 0x27, 0xc4, 0x2f, 0x31,
	0x9d, 0x03, 0xb6, 0xa0, 0x16, 0x4c, 0xa0, 0xb7, 0x57, 0x42, 0x4b, 0x03, 0xb3, 0xc8, 0xe2, 0x21,
	0x9d, 0x70, 0x49, 0x22, 0xb9, 0xfa, 0xf8, 0x2c, 0xef, 0xc0, 0x79, 0x8d, 0x34, 0xc4, 0x28, 0xd4,
	0xca, 0xe5, 0x2b, 0x91, 0x98, 0xf1, 0x2c, 0x34, 0xae, 0xec, 0x37, 0xbd, 0xc7, 0xcb, 0x07, 0xa5,
	0x94, 0x3f, 0x82, 0x9d, 0x09, 0xd3, 0x9e, 0x72, 0x8d, 0x2a, 0x67, 0x51, 0x9c, 0xb2, 0x3b, 0x79,
	0xf7, 0x7e, 0xed, 0x9e, 0x7f, 0x63, 0x0e, 0xcd, 0xef, 0xec, 0x96, 0xfa, 0xf3, 0xfc, 0x43, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x71, 0x42, 0x06, 0xe9, 0xa3, 0x0b, 0x00, 0x00,
}
